version: '3'
services:
  linkerd:
    image: buoyantio/linkerd:1.3.1
    command:
      - /io.buoyant/linkerd/config/config.yml
    volumes:
      - ./linkerd/config:/io.buoyant/linkerd/config
      - ./linkerd/disco:/io.buoyant/disco
    ports:
      - 9990:9990
  test:
    depends_on:
      - linkerd
    build: ./tester
    volumes:
      - ./tester/index.js:/test/index.js
